[package]
name = "advent7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent-common = { path = "../advent-common" }
anyhow = "1.0.66"
eyre = "0.6.8"
tracing = "0.1.37"
