[package]
name = "advent5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent-common = { path = "../advent-common" }
anyhow = "1.0.66"
log = "0.4.17"
regex = "1.7.0"
